{# Offer Instructions #}

<table align="center" cellpadding="0" cellspacing="0" border="0" width="600" bgcolor="#222222" style="background-color: #222222; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
    <tr>
        <td width="20"><!--spacer--></td>
        <td width="560" height="70" valign="middle" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.4 !important; text-align: center; font-size: 13px; color: #FFFFFF;">
            <p><b>Print out or show this email on your mobile device to receive these great offers!</b></p>
        </td>
        <td width="20"><!--spacer--></td>
    </tr>
</table>
