{# Single Column ( 560 ) #}

<table bgcolor="#FFFFFF" align="center" cellpadding="0" cellspacing="0" border="0" width="600" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-right: 1px solid #d5d5d5; border-left: 1px solid #d5d5d5;">
    <tr>
        <td width="20"><!--spacer--></td>
        <td width="560" valign="top">
            {# Insert 560 BLOCK(s) Here #}
            {% block block1 %}{% endblock %}
            {# END BLOCK(s) #}
        </td>
        <td width="20"><!--spacer--></td>
    </tr>
</table>
