{# Image Block Default #}

{% set width = width|default(560) %}
{% set height = height|default(315) %}

<table cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
    <tr>
        <td width="{{ width }}" height="{{ height }}" valign="top" class="imageBlockContents">
            {{ generate_image({
                width: width,
                height: height,
            }) }}
        </td>
    </tr>
    <tr>
        <td width="560" height="10"><!--spacer--></td>
    </tr>
</table>
