{% extends "layouts/screenshots.phtml" %}

{% set numColumns = 1 %}
{% set numRows = 6 %}

{% block main %}
    {# Header #}
    <div class="display-block-wrapper">
        <div class="display-block-column-header">Image Blocks</div>
    </div>

    {# Single Column Image Block #}
    <div class="display-block-wrapper">
        <div class="display-block-container">
            <div class="display-block-header"><h1>560</h1></div>
            {% embed "frames/single-column-560.phtml" %}
                {% block block1 %}
                    {% include "blocks/image-block-default.phtml" with { width: 560, height: 315 } %}
                {% endblock %}
            {% endembed %}
        </div>
    </div>

    {# Double Column Image Block #}
    <div class="display-block-wrapper">
        <div class="display-block-container">
            <div class="display-block-header"><h1>275 | 275</h1></div>
            {% embed "frames/double-column-275-275.phtml" %}
                {% block block1 %}
                    {% include "blocks/image-block-default.phtml" with { width: 275, height: 170 } %}
                {% endblock %}
                {% block block2 %}
                    {% include "blocks/image-block-default.phtml" with { width: 275, height: 170 } %}
                {% endblock %}
            {% endembed %}
        </div>
    </div>

    {# Double Column Image Block #}
    <div class="display-block-wrapper">
        <div class="display-block-container">
            <div class="display-block-header"><h1>370 | 180</h1></div>
            {% embed "frames/double-column-370-180.phtml" %}
                {% block block1 %}
                    {% include "blocks/image-block-default.phtml" with { width: 370, height: 208 } %}
                {% endblock %}
                {% block block2 %}
                    {% include "blocks/image-block-default.phtml" with { width: 180, height: 208 } %}
                {% endblock %}
            {% endembed %}
        </div>
    </div>

    {# Double Column Image Block #}
    <div class="display-block-wrapper">
        <div class="display-block-container">
            <div class="display-block-header"><h1>180 | 370</h1></div>
            {% embed "frames/double-column-180-370.phtml" %}
                {% block block1 %}
                    {% include "blocks/image-block-default.phtml" with { width: 180, height: 208 } %}
                {% endblock %}
                {% block block2 %}
                    {% include "blocks/image-block-default.phtml" with { width: 370, height: 208 } %}
                {% endblock %}
            {% endembed %}
        </div>
    </div>

    {# Triple Column Image Block #}
    <div class="display-block-wrapper">
        <div class="display-block-container">
            <div class="display-block-header"><h1>180 | 180 | 180</h1></div>
            {% embed "frames/triple-column-180-180-180.phtml" %}
                {% block block1 %}
                    {% include "blocks/image-block-default.phtml" with { width: 180, height: 101 } %}
                {% endblock %}
                {% block block2 %}
                    {% include "blocks/image-block-default.phtml" with { width: 180, height: 101 } %}
                {% endblock %}
                {% block block3 %}
                    {% include "blocks/image-block-default.phtml" with { width: 180, height: 101 } %}
                {% endblock %}
            {% endembed %}
        </div>
    </div>
{% endblock %}
